name: First Workflow

on:
  push:
    branches:  
      - main
jobs:
  example-jo:
    runs-on: ubuntu-latest

    steps:
      - name: print hello messsage
        run: echo "welcome to our first Github actions workflow"
      
      
