name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose the environment"
        required: true
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print message of deploy
        run: echo "The system is deployed to ${{ github.event.inputs.env }}"