name: Deployment Workflow

on:
  repository_dispatch:
    types: [incident_report]
jobs: 
  handle_incident:
    runs-on: ubuntu-latest
    steps:
      - name: print inicdent details
        run: echo "Incieent reported"